#!/bin/bash

# first argument is commit message
m=("-m" \"$1\")

# subsequent arguments are coauthors of commits
for ((i = 2; i <= $#; i++ )); do
m+=("-m" \"co-authored-by: ${!i}\")
done

eval "git commit ${m[@]}"